version: '3.8'

services:
  # The DynamoDB Local database service
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000" # Expose port 8000 for database access
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /data"
    volumes:
      - ./dynamodb_data:/data # Use a bind mount for data persistence

  # The service to initialize the database
  init:
    build:
      context: .
      dockerfile: dbinit-Dockerfile
    # The command now uses the wait script to ensure DynamoDB is ready
    # before running the python initialization script.
    command: ["/app/wait-for-it.sh", "dynamodb", "--", "python", "db_init.py"]
    depends_on:
      - dynamodb # Still useful to control startup order

  # The FastAPI application service
  api:
    build:
      context: .
      dockerfile: api-Dockerfile
    ports:
      - "8001:8000"
    environment:
      - IS_LOCAL=true
    # The command is now defined in the api-Dockerfile, which includes the wait script.
    # We still use depends_on to manage startup order and dependencies.
    depends_on:
      - dynamodb # Control startup order
      - init     # Ensure init runs before the api starts
