version: '3.8'

services:
  # The DynamoDB Local database service
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000" # Expose port 8000 for database access
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /data"
    volumes:
      - ./dynamodb_data:/data # Use a bind mount for data persistence
    # Add a healthcheck to ensure the DynamoDB service is fully running
    # and ready to accept connections before other services start.
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 5s
      timeout: 5s
      retries: 5

  # The service to initialize the database
  init:
    build:
      context: .
      dockerfile: dbinit-Dockerfile
    depends_on:
      dynamodb:
        condition: service_healthy


  # The FastAPI application service
  api:
    build:
      context: .
      dockerfile: api-Dockerfile
    ports:
      - "8001:8000"
    environment:
      - IS_LOCAL=true
    depends_on:
      dynamodb:
        condition: service_healthy
  
